### ISSUE TITLE
[Internationalization] Allow translating the game name.

### ISSUE THREAD

**Issue by Gallaecio** [Bertram25/ValyriaTear#203]
Although this might surprise some people, sometimes game names are translated. And I certainly intend to do so with “Valyria Tear” when translating into Galician (“A bágoa de Valïria”, pretty, isn’t it? :).

So I would like to be able to do so. This would require not only making instances of the game name translatable (such as the one that puts the game name on the game window), but it would also mean to allow translating the game logotype that appears on the main menu.

For the logotype translation, I suggest following the approach that they follow in The Battle for Wesnoth. At runtime, for certain images, they check whether the target file is available at “location/l10n/<languageCode>/filename.png”, and if it’s not, they just take it from “location/filename.png” instead.

They also provide extended documentation on how to localize these resources that might be helpful here as well: http://wiki.wesnoth.org/ImageLocalization

**Comment by Bertram25** [comment]
Setting to 1.1 since It's almost done.

**Comment by Gallaecio** [comment]
Awesome! I’ve been focusing on the translation of a different project for quite some time, and I’ve just now found out about this as I was updating the Galician translation.

It would be awesome if you could let me know which font you used for the original title, so I can try to use that font as well. Any other information on how to achieve a similar look to the original title is much appreciated.

**Comment by Bertram25** [comment]
> It would be awesome if you could let me know which font you used for the original title, so I can try to use that font as well. Any other information on how to achieve a similar look to the original title is much appreciated.

Hey @Gallaecio long time no see, indeed. ;)

I used the following font: http://www.dafont.com/fr/scriptina.font

About how I did it: The logo is made of two parts: A golden effect (but a bit darker than of the tutorial)
https://www.gimp.org/tutorials/Golden_Text/

I also duplicated the text before and traced it using a somewhat bigger brush using the brown color you can see around the gold.

Good luck! ;)
