### ISSUE TITLE
wiki lacks a page for configuration stuff

### ISSUE THREAD

**Issue by bmorel** [Bertram25/ValyriaTear#304]
Of course, most of configuration items are accessible through the GUI... but since the implementation of configurable text display speed, this is no longer true.

Plus, as I said somewhere in code or commit messages, *not all* display speeds are affected: menu speed is not, for example, and behavior for treasure chests have changed ( previously, it was faster than others, with 50 c/s against 30 c/s ).
So I think writing it somewhere accessible to normal users would be a good idea.

**Comment by Bertram25** [comment]
I'll close this issue as the message speed problem not being changed as been fixed (aka a GUI option has been added and the text scrolling speed is adapting itself after a change:
https://github.com/Bertram25/ValyriaTear/commit/1fd5d0732c1ab7eb2fdccdea9ccf75b41f097b67
https://github.com/Bertram25/ValyriaTear/commit/be887447713ae4217dd140b5e3683cde8951b382

I'll work on the wiki doc part sooner or later. Let's say that specific pages request can be issued while config files are usually self-documented.
