### ISSUE TITLE
Game freeze upon saving with realloc() error

### ISSUE THREAD

**Issue by akien-mga** [Bertram25/ValyriaTear#354]
When saving the game, I got the "Save successful!" message, but the game freezes on it (music continues playing, but I can't go back to the game, I'm stuck with the "Save successful!" popup).

In the terminal, I get this error log:
```
*** Error in `./src/valyriatear': realloc(): invalid next size: 0x000000000612a690 ***
```

**Comment by Bertram25** [comment]
Closing as duplicated of #463 It seems there must be some memory mishandling mostly in the map mode code and possibly also in luabind.
It will be investigated there.
