### ISSUE TITLE
Add battle 'Rush' option

### ISSUE THREAD

**Issue by Bertram25** [Bertram25/ValyriaTear#371]
The rush option or likely named makes every characters attack the first default enemy.

This is some kind of attack shortcut for the whole team.

**Comment by Suitecake** [comment]
Shouldn't the battle menu be directly tied to the BattleMode class rather than CommandSupervisor? It seems like the menu should be able to be opened both when the battle state is BATTLE_STATE_NORMAL (IE, when no CommandMenu is active for any character), as well as when a CommandMenu is active. If I understand the CommandSupervisor class correctly, making it openable when the battle state is BATTLE_STATE_NORMAL requires logic in BattleMode::Update().

**Comment by Bertram25** [comment]
Hi @Suitecake :)

And Happy New Year! As for your question. Honestly, it all depends on how you implement it ultimately.
Now, be it using the command supervisor, a new component or the battle mode itself, is just a matter of taste IMHO.
If you'd rather have the code within the battle mode class for simplicity, I don't mind at all. Just try to put your new code into clean functions if possible.
The best would be, still IMHO, to use a custom new object for that, as a new component of the battle mode, and update/render it when necessary. But it's definitely up to your sense of what's best. :)

At the end of the road, if your implementation looks sane, the most simple possible, doesn't add heavy or obscure dependencies and is working, you've won. Sorry, I can't actually tell more without doing the job myself, though.

Best regards and good luck. :)

**Comment by Suitecake** [comment]
No worries, thanks for the comment and Happy New Year!

**Comment by Suitecake** [comment]
I've got a working implementation. Now I'm just running through the game, using Rush every battle to make sure there isn't weirdness (such as in battles that contain dialog, if any exist). I hope to have that finished this weekend and have a pull request ready for review.

**Comment by Bertram25** [comment]
Cool :) Eager to see all that.

**Comment by Bertram25** [comment]
Rush was renamed Auto-Battle and will make characters use their default attack endlessly until the user opens a command menu, deactivating the auto-battle mode.

What's left to do is:
- Add an indicator in game that the auto-battle mode is active.
- Add icons to the battle menu item. (Soon escape will come, too.)
- Add a message box to the battle menu explaining the current option, just like the options menu does.

Thanks to @Suitecake for the initial effort and his patience about it. :)

**Comment by Bertram25** [comment]
Final part done with: 5d53d569449a98b87edb2536f7399bd79951a65f
