### ISSUE TITLE
Improve English text for episode 1 release

### ISSUE THREAD

**Issue by rootslinux** [Bertram25/ValyriaTear#420]
I mentioned this several months ago to Bertram that there were a number of glaring errors and grammatical mistakes in the English text of the most recent release. I promised to go through and proof read all the text, but I only got part of it finished and then got busy with other things. I'm working on finishing what I started now, making minor changes to the wording and grammar of all text seen in the game. You can see what I've done so far by looking into my master branch. I believe the only thing I have left to go through now are the map files, which I started working on this afternoon. 

I believe that every line I change will cause the corresponding line in a translation to be marked as "fuzzy", meaning that they will have to be rechecked. I don't think that the translations will need any updating, but translators should go through their text when this issue is closed.

Bertram: one thing I've left alone is that you seem to be capitalizing a lot of words that I wouldn't expect to. For example, in skill descriptions you have text like: "Deals damage with Fire and Wind elemental". You capitalize every damage/elemental type everywhere. This isn't correct and I wouldn't do it, but I'm not sure if you wanted it this way to emphasize these properties so I left them alone.

**Comment by Bertram25** [comment]
Done now #423 is rebased and merged. :)
