### ISSUE TITLE
Shall we keep SDL_Delay (10)?

### ISSUE THREAD

**Issue by Bertram25** [Bertram25/ValyriaTear#421]
Now we're using SDL 2.0, @authenticate pointed out that the sdl delay call in the main loop should be removed to let the game run at full capacity, and this can be compensated by setting vsync support to on.
Yet, I wonder whether this will be nice enough with cpu usage. Some research and tests are definitely needed here to sort this out.

**Comment by authenticate** [comment]
Happy New Year!  :)

I did a quick test with VSync and CPU usage.

I think, when VSync is enabled, the graphics drivers actually block the render thread such that the render thread can only present to the render target at the refresh interval.

So, this is effectively a frame rate limiting implementation.  It's already implemented by the driver itself.

(Note: However, I do not have any documentation to directly confirm this.)

As an example, here is VT built with full optimizations with SDL_Delay removed:

![release_vt](https://cloud.githubusercontent.com/assets/4543259/5592779/7c2a0d1a-91b0-11e4-8f75-17eb5ee67bbd.png)

It's running at ~1000 FPS and consuming ~1/8 (~12.5%) CPU.  This machine has 8 cores.  So, this data intuitively makes sense.  One thread, the main thread, is maxed while some additional CPU resources are being consumed probably by the OS's internal windowing and input systems.

Here's the VSynced version of the same build:

![release_vt_vsync](https://cloud.githubusercontent.com/assets/4543259/5592791/63c68162-91b1-11e4-9bdd-2700cc219a2b.png)

It's FPS capped to the refresh rate and uses a lot less CPU, which is more or less the implementation I think you are looking for.

Have a good one. :)

**Comment by Bertram25** [comment]
@authenticate Late answer but I am here. ;) Thanks for the tests.
Ok, I'll take into account that the vsync mode does cap the fps to the rendering refresh rate due to the current implementation.
Thus, if the vsync is on, the update mode won't use SDL_Delay calls.

**Comment by Bertram25** [comment]
Ok, what's left is to make the update loop style a visible option in the video settings, disabled when vsync is on (or on swap tearing).
