### ISSUE TITLE
Resolution - Window Mode Bug

### ISSUE THREAD

**Issue by authenticate** [Bertram25/ValyriaTear#429]
Hi,

This is a minor bug.

If I load the game in windowed mode and switch to full screen mode, the game will change from 800 x 600 resolution to 1024 x 768 automatically (this is fine).  Now, if I switch back to windowed mode, the resolution will remain at 1024 x 768 (this is also fine).  However, if I open the "Resolution: X" option in the menu, the resolution will be selected at 800 x 600.  This is incorrect.  The resolution within the menu still reflects the original 800 x 600 resolution and not the current 1024 x 768 resolution.

**Comment by Bertram25** [comment]
True :) Thanks for spotting.
