### ISSUE TITLE
Portable binary release for Linux

### ISSUE THREAD

**Issue by akien-mga** [Bertram25/ValyriaTear#431]
Now that I've learned how to make portable binary releases for OpenDungeons, I thought I could probably edit my scripts a bit and create portable binaries for ValyriaTear 1.0.0. WDYT?

You could then also use them to get VT on Lutris: https://lutris.net/

**Comment by akien-mga** [comment]
Well since I had the scripts and chroots at hand, I had a go at making a 32bit binary release: http://remi.verschelde.fr/files/misc/ValyriaTear-1.0.0-linux-i586.tar.bz2 :-)

**Comment by Bertram25** [comment]
Cool thanks :)
I'll test that one asap.

**Comment by Bertram25** [comment]
@akien-mga Do you want me to have a go at creating a binary release for x64, btw?

**Comment by akien-mga** [comment]
I can start a build right now, the scripts are the same for both archs :-)

**Comment by akien-mga** [comment]
Here it is: http://remi.verschelde.fr/files/misc/ValyriaTear-1.0.0-linux-x86_64.tar.bz2

This is a first try, IMO I bundled too many libraries (I'm not sure about libgii, libggi and stuff like that). I'll have to check which libraries are installed by default on a "normal" system with a graphical server, so that I can remove some of the redundant bundled libraries.

**Comment by akien-mga** [comment]
It's now online :-)

**Comment by akien-mga** [comment]
I tried the 32Bit portable binary on a freshly-installed 32bit Mageia 5 beta 3, installed using a sysadmin-oriented "dual arch" 1,2 GB DVD (i.e. there's about only 600 MB worth of 32bit packages on it, and it makes a minimal install with XFCE).

At first the game crashes because I had no pulseaudio server installed, so I installed it and VT worked fine.

Then I checked the available "out of the box" libraries on the system, and there's quite a lot of stuff that could be unbundled if we can confirm that it's present on most typical Linux systems: https://framalab.org/zerobin/?e095b063fd533c23#MpJF0Pn6QREXlYtigvtEJGBhcTCHdN9jk+wCudackNU=

The bundled libs prefixed with "sys" are the ones available on the system.

I'm surprised to see SDL 1.2 installed out of the box, but I think I'll keep it bundled anyway so that the version is sure to be the same as the one SDL_ttf and SDL_image were built again. What do you think about the rest?

**Comment by Bertram25** [comment]
There are a lot of libs I'm not that fluent with. I was ICE would be among the sys ones since it's quite used. As for the rest, I'm surprised a few X ones are part of the system while other aren't, since it's quite a monolithic thing. Is it bad if you don't remove some of them?

Keeping SDL is also a very good idea, indeed. Especially as SDL is moving forward to 2.0/2.1. :) 

I tried the x64 build and it is working like a charm. :D Do you want me to upload it somewhere, on lutris, for instance? (Or do you already have an account there?)

Thanks again for the help.

**Comment by akien-mga** [comment]
Not that the ones without the "sys" prefer but with a path like /lib/libfoo.so.1 are also system libs, I just did not consider them when comparing, hence the missing "sys" symbol. So most X libs are not bundled, I just made a mistake with libxcb.so.1 and libXxf86vm.so.1.

I'll do cleaned up builds with less low-level bundled libraries.

**Comment by akien-mga** [comment]
I've uploaded the cleaned up builds at the same URLs:
- http://remi.verschelde.fr/files/misc/ValyriaTear-1.0.0-linux-i586.tar.bz2
- http://remi.verschelde.fr/files/misc/ValyriaTear-1.0.0-linux-x86_64.tar.bz2

Removing unnecessary libraries only gained us 2 MB, but I think the less bundled libraries, the better (as long as there is the necessary stuff though). In the end, Valyria Tear is quite lightweight when it comes to the libraries it uses:
```
lib/libdirect-1.6.so.0
lib/libdirectfb-1.6.so.0
lib/libfusion-1.6.so.0
lib/liblua.so.5.1
lib/libopenal.so.1
lib/libpng15.so.15
lib/libSDL-1.2.so.0
lib/libSDL_image-1.2.so.0
lib/libSDL_ttf-2.0.so.0
```

I've tried the 32bit build on the same VM as previously, and it works fine.
The 64bit works fine on my main desktop.

> Do you want me to upload it somewhere, on lutris, for instance? (Or do you already have an account there?)

If you can confirm that the 64bit build works, maybe you can upload both to SourceForge (when it's back online, it seems to be down right now)? Then I can use the SourceForge download link directly to create the installer scripts for Lutris.

BTW, pro tip: with SourceForge you can write download links as e.g. ```http://downloads.sf.net/valyriatear/ValyriaTear-1.0.0-linux-x86_64.tar.bz2``` (i.e. sf/projectname/filename, without having to name the potentials subfolders in the files section). Not sure it would be useful to you, but it's a packager's pro tip that I'm trying to make know :-D

**Comment by akien-mga** [comment]
Well thinking again about it I might have been a bit drastic, I think I'll readd the sound (ogg, vorbis, vorbisfile) and image related libraries (jpeg, tiff, jbig) + freetype. Those are installed by default on a minimal Mageia 5 system, but that doesn't mean that _everybody_ has them :-)

**Comment by akien-mga** [comment]
Another thing: the binary content (valyriatear executable + bundled libs) is about 12 MB. I wonder if it wouldn't be more convenient for users to put both the i586 and x86_64 builds in the same folder, one using a ./lib RPATH and the other one a ./lib RPATH?

**Comment by Bertram25** [comment]
>  Not sure it would be useful to you, but it's a packager's pro tip that I'm trying to make know :-D

thanks for the tip. :) I'll upload once both builds ans SF are fine? ;) Sometimes tomorrow, hopefully.

> I wonder if it wouldn't be more convenient for users to put both the i586 and x86_64 builds in the same folder, one using a ./lib32 RPATH and the other one a ./lib64 RPATH?

Not sure I get the point but, why would someone want to download both game versions?

**Comment by akien-mga** [comment]
> Not sure I get the point but, why would someone want to download both game versions?

The idea was to prevent having to generate two 95MB tarballs (with ~80 MB data) and generate only a big ~110 MB tarball with both arches included.

Then there could be some kind of helper script (e.g. ValyriaTear.sh) that would launch either the 32bit or 64bit binary depending on the user's arch.

Another possibility is to simply drop ix86 support because hey, Linux users should all be on x86_64 by now :-)

**Comment by akien-mga** [comment]
Either way, I've played around with my bash scripts so that both single arch and dual arch tarballs can be generated :-) It's up to you to chose the flavour now, it's your game :-D

**Comment by Bertram25** [comment]
Thanks, it's a nice start of a game, I'd rather say? XD In any case, I'll upload both to lutris if I can. Do you sill want to play a bit with this or is this ok for you so far? (I'll upload tomorrow if it is.) :)

**Comment by akien-mga** [comment]
I'm just finished tuning my scripts to be able to produce a "dual arch" tarball. It was a nice bash learning experience :)
Which type would you prefer? Two single arch tarballs or a slightly bigger tarball with both arches and a script that chooses the correct one?

**Comment by akien-mga** [comment]
All three flavours are now online:
- 32bit: http://remi.verschelde.fr/files/misc/ValyriaTear-1.0.0-linux-i586.tar.bz2
- 64bit: http://remi.verschelde.fr/files/misc/ValyriaTear-1.0.0-linux-x86_64.tar.bz2
- 32bit & 64bit: http://remi.verschelde.fr/files/misc/ValyriaTear-1.0.0-linux.tar.bz2

**Comment by Bertram25** [comment]
Wow, nice stuff. :) I guess I'll go for the simplest option (uploading the 586 + x64 files). Lutris, here we come. ;)

**Comment by akien-mga** [comment]
For Lutris, do you want to handle it or should I do it?

If you want to have a go at it, you have to:
- Create an account if you don't have one yet
- Submit a new game: https://lutris.net/games/add-game/
- Then your game will be "unpublished" and waiting for moderation, but you will already be able to access it here: https://lutris.net/games/valyriatear
- On the newly created page, click "Write a new installer" and just do something similar to the installer script of OpenDungeons: https://lutris.net/games/opendungeons/
e.g. for 64bit:
```
exe: valyriatear.x86_64
files:
- game: http://downloads.sf.net/valyriatear/ValyriaTear-1.0.0-linux-x86_64.tar.bz2
installer:
- extract:
    file: game
```

**Comment by Bertram25** [comment]
Ok, thanks for ALL the help about this. It's very cool. :sunglasses:

**Comment by Bertram25** [comment]
Ok, I've added the game on lutris, the installer for x64 and a few screenshots.

The thing is I don't like the quick-done banner I've added and I shouldn't added Windows as a lutris platform, but I can't change that atm.
I'll try again once the game is approved (hopefully).

**Comment by akien-mga** [comment]
You should probably ask the lutris guys directly on #lutris then, I think you can't edit the banner and game description after you've submitted it, only the screenshots and installer scripts.

Just ask strycore or Xodetaetl on #lutris.

**Comment by akien-mga** [comment]
Two things still:
- Maybe you could add a link to the portable binaries in your download section? http://valyriatear.blogspot.fr/p/downloads.html
- And maybe make the 64bit binary the default Linux download on SF instead of the 32bit one, if there are still Linux users using ix86, they'll have to find their way :)

**Comment by Bertram25** [comment]
> - Maybe you could add a link to the portable binaries in your download section? http://valyriatear.blogspot.fr/p/downloads.html

Yep, just done it. :)

>- And maybe make the 64bit binary the default Linux download on SF instead of the 32bit one, if there are still Linux users using ix86, they'll have to find their way :)

A mistake o'mine. Now fixed. Thanks a lot for pointing out. :)

**Comment by Bertram25** [comment]
> Just ask strycore or Xodetaetl on #lutris.

Ok, I'll have a look asap. Thanks! :)

**Comment by Bertram25** [comment]
New VT banner, hopefully better once cropped on Lutris:
![vt_banner](https://cloud.githubusercontent.com/assets/765917/6199033/8d567e60-b42a-11e4-9388-9d310d318491.png)

**Comment by akien-mga** [comment]
It's gorgeous :)

**Comment by Bertram25** [comment]
The game is released on Lutris, and the banner has been fixed. I'm gladly closing this one. :D
