### ISSUE TITLE
Crash on fighting spider after first Fenrir boss fight

### ISSUE THREAD

**Issue by Suitecake** [Bertram25/ValyriaTear#432]
(Windows 32-bit build running on Windows 7 64-bit (using authenticate's dependencies bundle))

I'm getting a crash on contact with a spider mob after the first Fenrir boss fight in the forest.

Call stack:
ValyriaTear.exe!vt_audio::AudioDescriptor::GetFilename() Line 225
ValyriaTear.exe!vt_battle::TransitionToBattleMode::Reset() Line 1369
ValyriaTear.exe!vt_mode_manager::ModeEngine::Update() Line 312
ValyriaTear.exe!SDL_main(int argc, char * * argv) Line 577
[...]

It looks like the AudioDescriptor instance returned by AudioManager->GetActiveMusic() is NULL / not initialized.

**Comment by Suitecake** [comment]
Is this as simple as adding a null reference check, or does this point to an underlying problem?

**Comment by Suitecake** [comment]
The background music dies down before the Fenrir fight, and does not come back until you leave the screen. If you leave the screen and then come back and fight the spider, there's no crash.

I'll investigate this further and see if I can find a fix.

**Comment by Bertram25** [comment]
My recent changes to the audio system may have left out a few bugs. So thanks a lot for testing the feature with game runs. (Tests are so desperately needed with new features.)

> The background music dies down before the Fenrir fight, and does not come back until you leave the screen. If you leave the screen and then come back and fight the spider, there's no crash.

From your latest comment, it would lead me to think the music pointer is NULL because there is not music and I didn't think about it when coding, but who knows? I'll have a look as well. Thanks for the report in any case. :)

**Comment by Suitecake** [comment]
For sure!

It definitely does sound like the music pointer is NULL. I think I know where to put the check; I'll see if I can fix it up and send a pull request tonight.

**Comment by Bertram25** [comment]
It was definitely a missing null check for that case. The music was null but used anyway.
