### ISSUE TITLE
Intermittent crash to main menu on map change

### ISSUE THREAD

**Issue by Suitecake** [Bertram25/ValyriaTear#433]
Windows 32-bit build on Windows 7 64-bit (using authenticate's dependencies bundle)

I'm getting a crash to main menu on map changes every so often. I've seen it happen in the forest as well as in the opening village.

When running in Debug, the output pane displays:

First-chance exception at 0x76F2C42D in ValyriaTear.exe: Microsoft C++ exception: luabind::cast_failed at memory location 0x0028CA70.
First-chance exception at 0x76F2C42D in ValyriaTear.exe: Microsoft C++ exception: luabind::cast_failed at memory location 0x0028CA70.
First-chance exception at 0x76F2C42D in ValyriaTear.exe: Microsoft C++ exception: luabind::cast_failed at memory location 0x0028CA70.
First-chance exception at 0x76F2C42D in ValyriaTear.exe: Microsoft C++ exception: luabind::cast_failed at memory location 0x0028CA70.

**Comment by Suitecake** [comment]
This crash is now occurring every time I attempt to exit the west side of the first map immediately after the first encounter with Fenrir (the west exit from larya_forest_south_east, I think)

**Comment by Bertram25** [comment]
Nice catch. I'll have a look.

**Comment by Bertram25** [comment]
Normally, this is fixed with 7fb94914b260e48ae0a8459c1c49a54c29cababd thanks to your feedback.

In any case, feel free to reopen if the commit doesn't fix the crash as the issue is looking slightly more twisted here. And thanks a lot for the feed-back :D
