### ISSUE TITLE
Crash on loading map Load() layna_forest_cave1_1_script.lua

### ISSUE THREAD

**Issue by Suitecake** [Bertram25/ValyriaTear#438]
I'm seeing a crash on entering the layna forest cave (following Orlinn).

SCRIPT_DEBUG text:

DEBUG:c:\src\valyriatear\src\engine\script\script_read.cpp:vt_script::ReadScriptDescriptor::OpenFile:49: 
Reading img/sprites/map/objects/rock1.lua
ERROR:c:\src\valyriatear\src\engine\script\script.cpp:vt_script::ScriptEngine::HandleLuaError:83: 
a runtime Lua error has occured with the following error message:
  
ERROR:c:\src\valyriatear\src\engine\script\script.cpp:vt_script::ScriptEngine::HandleLuaError:85: 
attempt to call a nil value
ERROR:c:\src\valyriatear\src\modes\map\map_mode.cpp:vt_map::MapMode::_Load:671: 
Invalid map Load() function in dat/maps/layna_forest/layna_forest_cave1_1_script.lua. The function wasn't called.
DEBUG:c:\src\valyriatear\src\engine\script\script_read.cpp:vt_script::ReadScriptDescriptor::OpenFile:49:

**Comment by Bertram25** [comment]
Thanks a lot @Suitecake :) I'll fix that regression asap.

**Comment by Bertram25** [comment]
From a quick glance, the DialogueManager reference and related calls should have been removed.
The rest of the file looks fine. I'll fix this tonight.
