### ISSUE TITLE
Village fight with Lord Banesore is losable

### ISSUE THREAD

**Issue by Suitecake** [Bertram25/ValyriaTear#446]
The village fight with Lord Banesore (after the encounter with the crystal in Layna Forest) is losable. Lilly will heal Bronann if he's low on health, but it's possible for Lord Banesore to do enough damage to wipe out Bronann.

It's frustrating for the user to have to either hope Lilly heals enough (and so Bronann can make it through the fight), or to have to use healing potions on a scripted fight. It would be better for the fight to be completely unlosable (perhaps by scaling up Lilly's healing, or perhaps by villagers tossing Bronann healing potions each time he uses one).

**Comment by Bertram25** [comment]
I'll be honest, I've made the battle losable on purpose, in case the player was a bit too much careless about it, so he has to stay cautious facing that big villain.
Is there a point completely blocking you in this battle or is it a matter of taste?

**Comment by Suitecake** [comment]
This is purely a matter of taste, so I defer to you here. It seemed like the sort of thing that could slip through even if it wasn't intended (IE, adjusting when and how much Lilly heals the PC). I do think this is unfriendly by modern sensibilities (it definitely feels classic), but given the ability to immediately Retry a battle, it isn't an issue.

In my case, it came up because I'm Rush-ing every battle to test that it works correctly, and perhaps it's appropriate that the player could be punished for trying to rush a battle like this =p

**Comment by Bertram25** [comment]
> I do think this is unfriendly by modern sensibilities (it definitely feels classic), but given the ability to immediately Retry a battle, it isn't an issue.

Ok, as we now have game difficulty support, I'll definitely tune this for the easy/casual mode.
I will also rename easy to casual, btw.

**Comment by Bertram25** [comment]
> I will also rename easy to casual, btw.

N.B.: I'll let easy after all, as casual is either easier than easy, or rather a name taken from the app world.
