### ISSUE TITLE
Game does not recognized reconnected gamepad

### ISSUE THREAD

**Issue by Suitecake** [Bertram25/ValyriaTear#447]
Game does not recognize gamepad if disconnected then reconnected. The user must open the menu and toggle Input Enabled from Yes to No and back to Yes for the gamepad to be recognized again.

If possible, the game should recognize the gamepad immediately after its reconnected. If that isn't possible, the game should set gamepad Input Enabled to No (as it correctly does if the game starts up and no gamepad is connected).

**Comment by Suitecake** [comment]
(I'm investigating a fix for this)

**Comment by Bertram25** [comment]
Thanks for PR about this :) (In #449)

**Comment by Bertram25** [comment]
Fixed with #449
