### ISSUE TITLE
Crash on main menu when first toggling Input Enabled with 360 controller connected

### ISSUE THREAD

**Issue by Suitecake** [Bertram25/ValyriaTear#448]
I'm getting an AccessViolation exception when first toggling Input Enabled in the options menu with a 360 controller connected (Windows 7 64-bit).

**Comment by Suitecake** [comment]
I have not seen this issue while in-game; only on the main menu, and only immediately after opening the game. If a game is started or loaded and then I exit back to the main menu, toggling the Joystick's Input Enabled in the main menu does not cause an AccessViolation.

Something's not getting initialized right; I'll investigate this too while working on #447

**Comment by Bertram25** [comment]
@Suitecake Does your fix in #449 fix this issue, too?
(I can't reproduce so I'll need your help on that one.)

**Comment by Suitecake** [comment]
It does, I think. I'll double-check when I get home

**Comment by Bertram25** [comment]
Closed with #449 . Feel free to reopen if it's not the case. :)

**Comment by Suitecake** [comment]
Verified that this exception is no longer occurring on a clean master build

**Comment by Bertram25** [comment]
Cool, thanks for the test. :)
