### ISSUE TITLE
Skeleton and spikes in 8-ball puzzle are annoying (Mt Elbrus)

### ISSUE THREAD

**Issue by Suitecake** [Bertram25/ValyriaTear#451]
Another matter of taste =p

The roaming skeleton and the spikes in the 8-ball puzzle are really, really annoying. It wouldn't be so bad if the skeleton didn't respawn.

If a mixture of combat and puzzling is desired, one alternative would be a button for resetting the puzzle (instead of having to leave and re-enter the area, which is weird), but also spawns a skeleton.

**Comment by Bertram25** [comment]
As said in the other one, part of another issue.
The skeleton should spawn only in hard mode. ;)

**Comment by Suitecake** [comment]
I approve of this =D

**Comment by Bertram25** [comment]
Cool :) I'll deal with that one asap as many people are requesting it. ;)
