### ISSUE TITLE
Enemies can spawn inside puzzle balls (Mt Elbrus)

### ISSUE THREAD

**Issue by Suitecake** [Bertram25/ValyriaTear#452]
It's possible for enemies to spawn inside a puzzle ball. Weird visually. Not sure if they're unable to move (when I saw it, I pushed up against the ball to see if it would trigger a battle).

Battle happened too quickly to capture a screenshot. Observed at the 8-ball puzzle in Mt Elbrus.

**Comment by Bertram25** [comment]
Yes, part of another issue. I'll fix that after the data reorganization. :)

**Comment by Bertram25** [comment]
Probably linked to the collision detection algorithm. I'll fixed that along with other things.

**Comment by Bertram25** [comment]
I've tested the algorithm. The detection of the rolling stones before spawning the enemy is done and working fine as far as I tested.
My best guess is that the spawn location was set while the ball was moving and finished once it was there.
I'll reduce the spawn area for now and will consider it "fixed". If my guess is wrong, feel free to reopen and tell more. :)
