### ISSUE TITLE
C++11 - Here we go!

### ISSUE THREAD

**Issue by Bertram25** [Bertram25/ValyriaTear#464]
After some push from @bmorel, I think he's right. It's time to open the door to c++11

- [x] Adapt CmakeLists.txt
- Adapt the code following the new convention - can be done little by little.

If you have problems with the VT codebase because of the new c++11 norm, please post here, so I can get aware of platforms with such dilemma in compiler support.

N.B.: Seems @bmorel was absorbed in a black hole. I'd say ask support to reinstate you, mate. :)

**Comment by rootslinux** [comment]
FYI, a few months ago I converted the Allacrost code to C++11 without many problems. Of course I didn't go through the entire code and rewrite things to use new features or anything, but I did begin using those features in new code that was being written.

**Comment by Bertram25** [comment]
I think it's a sane way to do it. Actually, this is not a big goal for now, just a notice to say the door is now open. ;)

**Comment by Bertram25** [comment]
From @Suitecake 

> Looks like C++11 isn't enabled yet on Travis-CI

This needs to be done.

**Comment by Bertram25** [comment]
Also done with #474

**Comment by Bertram25** [comment]
Done with ee786f9 . More can be done little by little.
