### ISSUE TITLE
Possible collision problems in Andromalius area

### ISSUE THREAD

**Issue by bmorel** [Bertram25/ValyriaTear#466]
I have noticed that, sometimes, I die from spikes in Andromalius area, even if I am running against the wall, spiked being in the other direction, like this:

||<-[]

||: wall
<-: running character
[]: spikes

I have only noticed this when trying to reach lateral stones. I would guess a collision problem, but it's only a guess. It's quite hard to reproduce with exact steps.

**Comment by Bertram25** [comment]
Ok, I'll reduce Orlinn's collision width a bit.:
![screenshot_3](https://cloud.githubusercontent.com/assets/765917/7759846/82fc133a-0015-11e5-8d84-441477186ffe.png)
