### ISSUE TITLE
Andromalius' flames does not always disappear

### ISSUE THREAD

**Issue by bmorel** [Bertram25/ValyriaTear#467]
Since the last commit, things seems to work.
Now, when you send a stone to Andromalius, which only reach him when you are on your dying animation, on next try, Andromalius have 3 flames around him from the start. They are not moving, and do not prevent the next flames to fly on the character, so there is no big problem here.

**Comment by Bertram25** [comment]
ack, I'll have a look. Thanks for the feed-back.

**Comment by bmorel** [comment]
wow, fast!

**Comment by Bertram25** [comment]
I reproduced the context, this doesn't happen on my end. Are you able to reproduce it systematically?
I manage to do it from the south stone. Is it the same for you?

**Comment by bmorel** [comment]
I can't reproduce it either. I had the problem with the south stone, yes.

**Comment by Bertram25** [comment]
I'll close as can't reproduce for now. Feel free to open a new one if anything relevant. :)
