### ISSUE TITLE
translation not always used

### ISSUE THREAD

**Issue by bmorel** [Bertram25/ValyriaTear#469]
Just wanted to try some translating some strings, I had the surprise that almost everything is translated. Started a new game, just to be sure and... ok, some string which are translated in the po file, are not being shown in French in the game.
So it is probably a bug somewhere, maybe on my system. Don't know.

**Comment by akien-mga** [comment]
This would happen if, either:
1. Strings are marked as "fuzzy" in the PO file, i.e. they need to be proofread and maybe fixed
2. The translation is complete on Transifex but not in sync with git

**Comment by akien-mga** [comment]
Just checked, and there are indeed a good deal of fuzzy strings in the translation, most likely due to a POT update: https://github.com/Bertram25/ValyriaTear/blob/master/po/fr.po

**Comment by Bertram25** [comment]
Yep, that's because the translation manager doesn't do his job. (Aka me). I'll handle that asap.
