### ISSUE TITLE
When performing a special attack, player portrait temporarily shifts to bottom of action bar

### ISSUE THREAD

**Issue by Suitecake** [Bertram25/ValyriaTear#471]
When performing a special attack (such as Bronann's Forward Thrust), Bronann's portrait on the action bar shifts down to the bottom of the action bar for a second or two.

Beginning of attack:
![beginning-attack](https://cloud.githubusercontent.com/assets/1323568/7902141/40d4b3c8-077b-11e5-9a60-1049a819ea00.png)

During the attack animation:
![during-attack](https://cloud.githubusercontent.com/assets/1323568/7902142/4387cb3c-077b-11e5-8572-7e578ff16769.png)

**Comment by Bertram25** [comment]
Nice catch, I'll fix that asap.
