### ISSUE TITLE
Crash on exiting Andromalius puzzle room

### ISSUE THREAD

**Issue by Suitecake** [Bertram25/ValyriaTear#476]
The game crashes silently to main menu on exiting the Andromalius puzzle room (where Orlinn has to roll the balls into Andromalius)

**Comment by Bertram25** [comment]
Lol, this must be the most broken map script since the API change. I'll be on it. ;)

**Comment by Bertram25** [comment]
Thanks! I also checked for other misspelled sound object invocations and it should be ok now. :)
