### ISSUE TITLE
The F1 help in store does not help. 

### ISSUE THREAD

**Issue by shirishag75** [Bertram25/ValyriaTear#7]
The F1 document for store (as in buying and selling) tells nothing. It should tell how to complete the transactions. 

Also dunno if the price changes when you sell or buy too much of one thing (say minor health potions for now.)

**Comment by Bertram25** [comment]
As told in the latest commit, the shop mode has now got a first time tutorial, and the game has got an offline webpage manual.

I'm considering this oldie closed and will work on the online manual when the game has got more interesting mechanisms and if still needed (thanks to tutorial and such).
